export default {
	register: '/register',
	login: '/login',
	logout: 'logout',
	updateUserDate: 'doctorInfo/createOrUpdateInfo',
	createPatient: 'patients',
	getPatients: 'patients',
	searchPatients: 'patients/search',
	getSessions: 'getSessions',
	getSession: 'session',
	getComplaint: 'complaint/autoComplete',
	getHistory: 'history/autoComplete',
	getExamination: 'examination/autoComplete',
	getMedicine: 'medicine/autoComplete',
	getDoses: 'dose/autoComplete',
	getDiagnosis: 'diagnosis/autoComplete',
	getRequest: 'request/autoComplete',
	getNotes: 'note/autoComplete',
	getData: 'dashboard',
	todaySession: 'dashboard/todaySession'
};
