const AUTH_NAMESPACE = 'auth';
const PATIENTS_NAMESPACE = 'patients';
const PATIENT_NAMESPACE = 'patient';
const TEMPLATES_NAMESPACE = 'template';
const SESSION_NAMESPACE = 'session';
const LIST_NAMESPACE = 'list';
export {
	AUTH_NAMESPACE,
	PATIENTS_NAMESPACE,
	PATIENT_NAMESPACE,
	TEMPLATES_NAMESPACE,
	SESSION_NAMESPACE,
	LIST_NAMESPACE
};
